#!/usr/bin/env bash
#
# Unit-tests scripts/check-caller-conformance.sh (#346).
#
# The "healthy" fixture is generated by the REAL scaffold-caller.sh (no hand-copied
# stand-in — same principle as test-scaffold-caller-regression.sh), so it can never drift
# from the canonical stub set the check compares against. Each negative case mutates a
# copy of that healthy tree and asserts the expected advisory warning appears (and that the
# healthy tree stays clean). check-caller-conformance.sh always exits 0 (advisory), so the
# assertions are on its emitted `::warning::` lines, not its exit code.
set -euo pipefail

here="$(cd "$(dirname "$0")/.." && pwd)"
export CALLER_CONFORMANCE_ROOT="$here"
check="$here/scripts/check-caller-conformance.sh"
scaffold="$here/scripts/scaffold-caller.sh"

tmproot="$(mktemp -d)"
trap 'rm -rf "$tmproot"' EXIT

# Canonical healthy stub set, straight from scaffold-caller.sh.
healthy="$tmproot/healthy"
mkdir -p "$healthy"
bash "$scaffold" -o "$healthy" -w "" >/dev/null

fresh_copy() { # fresh_copy NAME -> echoes a path to a fresh mutable copy of the healthy tree
  local dst="$tmproot/$1"
  rm -rf "$dst"; cp -r "$healthy" "$dst"
  echo "$dst"
}

failures=0
# assert_has NAME DIR PATTERN — check(DIR) must emit a warning matching PATTERN.
assert_has() {
  local name="$1" dir="$2" pat="$3" out
  out="$(bash "$check" "$name" "$dir" 2>&1)"
  if printf '%s\n' "$out" | grep -qE "$pat"; then
    echo "ok   - $name"
  else
    echo "FAIL - $name (expected a warning matching: $pat)"; printf '%s\n' "$out" | sed 's/^/        /'
    failures=$((failures + 1))
  fi
}
# assert_clean NAME DIR — check(DIR) must emit NO warnings.
assert_clean() {
  local name="$1" dir="$2" out
  out="$(bash "$check" "$name" "$dir" 2>&1)"
  if printf '%s\n' "$out" | grep -q '::warning::'; then
    echo "FAIL - $name (expected no warnings)"; printf '%s\n' "$out" | sed 's/^/        /'
    failures=$((failures + 1))
  else
    echo "ok   - $name"
  fi
}
# assert_not NAME DIR PATTERN — check(DIR) must NOT emit a warning matching PATTERN.
assert_not() {
  local name="$1" dir="$2" pat="$3" out
  out="$(bash "$check" "$name" "$dir" 2>&1)"
  if printf '%s\n' "$out" | grep -qE "$pat"; then
    echo "FAIL - $name (unexpected warning matching: $pat)"; printf '%s\n' "$out" | sed 's/^/        /'
    failures=$((failures + 1))
  else
    echo "ok   - $name"
  fi
}

# 0. The scaffolded canonical set conforms to itself — zero findings.
assert_clean "healthy scaffold conforms" "$healthy"

# 0b. ci.yml legitimately job-chains claude-autofix.yml (autofix job); that must NOT be
#     mistaken for a dead standalone claude-autofix stub.
assert_not "job-chained autofix inside ci is not flagged" "$healthy" "dead stub 'ci|non-canonical stub 'ci"

# 1. (a) MISSING — drop a canonical stub.
d="$(fresh_copy missing-audit)"; rm -f "$d/audit.yml"
assert_has "(a) missing canonical stub (audit)" "$d" "no live caller stub wires audit\.yml"

# 2. (b) DEAD workflow_run stub — the exact R5/#263 class.
d="$(fresh_copy dead-autofix)"
cat > "$d/claude-autofix.yml" <<'YAML'
name: Claude autofix
on:
  workflow_run:
    workflows: [CI]
    types: [completed]
jobs:
  autofix:
    uses: SuxOS/.github/.github/workflows/claude-autofix.yml@main
    secrets: inherit
YAML
assert_has "(b) dead workflow_run autofix stub" "$d" "dead stub 'claude-autofix\.yml' triggers on workflow_run"

# 2b. (b) non-canonical stub NOT on workflow_run — softer message, still flagged.
d="$(fresh_copy noncanon)"
cat > "$d/bespoke.yml" <<'YAML'
name: Bespoke
on:
  push:
jobs:
  x:
    uses: SuxOS/.github/.github/workflows/health.yml@main
    secrets: inherit
YAML
assert_has "(b) non-canonical stub (non-workflow_run)" "$d" "non-canonical stub 'bespoke\.yml'"

# 2c. A bespoke workflow that wires NO SuxOS reusable is a repo's own business — not flagged.
d="$(fresh_copy own-deploy)"
cat > "$d/deploy.yml" <<'YAML'
name: Deploy
on:
  push:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: [{ run: "echo deploy" }]
YAML
assert_not "own non-SuxOS workflow is not flagged" "$d" "deploy\.yml"

# 3. (d) STALE REF — pin one stub off @main.
d="$(fresh_copy stale-ref)"
sed -i 's#workflows/audit.yml@main#workflows/audit.yml@v1.2.3#' "$d/audit.yml"
assert_has "(d) stale non-@main ref" "$d" "stub wires audit\.yml at @v1\.2\.3"

# 4. (c) MISSING secrets: inherit.
d="$(fresh_copy no-secrets)"
sed -i '/secrets: inherit/d' "$d/health.yml"
assert_has "(c) stub missing secrets: inherit" "$d" "caller stub 'health' is missing 'secrets: inherit'"

# 5. (c) security-review missing ready_for_review.
d="$(fresh_copy no-rfr)"
sed -i 's/, ready_for_review//' "$d/security-review.yml"
assert_has "(c) security-review missing ready_for_review" "$d" "security-review stub is missing the 'ready_for_review'"

# 6. A repo with no .github/workflows at all is reported, not crashed.
assert_has "no workflows dir at all" "$tmproot/does-not-exist" "no .github/workflows directory"

# 7. `self` mode (#356): .github's own self-*.yml stubs are legitimately named
#    self-<name>.yml, not <name>.yml — the naming-derived checks (a)/(c)/(d) and (b)'s
#    generic non-canonical branch must NOT fire on that prefix alone.
assert_self_has() {
  local name="$1" dir="$2" pat="$3" out
  out="$(bash "$check" "$name" "$dir" self 2>&1)"
  if printf '%s\n' "$out" | grep -qE "$pat"; then
    echo "ok   - $name"
  else
    echo "FAIL - $name (expected a warning matching: $pat)"; printf '%s\n' "$out" | sed 's/^/        /'
    failures=$((failures + 1))
  fi
}
assert_self_clean() {
  local name="$1" dir="$2" out
  out="$(bash "$check" "$name" "$dir" self 2>&1)"
  if printf '%s\n' "$out" | grep -q '::warning::'; then
    echo "FAIL - $name (expected no warnings)"; printf '%s\n' "$out" | sed 's/^/        /'
    failures=$((failures + 1))
  else
    echo "ok   - $name"
  fi
}

# 7a. Real .github/workflows/self-*.yml stubs (self-<name>.yml, self-fixer-30m.yml
#     variants, …) must not false-positive on naming alone.
assert_self_clean "self mode: real self-*.yml stubs conform" "$here/.github/workflows"

# 7b. A dead self-*.yml stub on workflow_run IS still caught (the whole point of #356).
d="$(fresh_copy self-dead-autofix)"
cat > "$d/self-claude-autofix.yml" <<'YAML'
name: Self claude autofix
on:
  workflow_run:
    workflows: [CI]
    types: [completed]
jobs:
  autofix:
    uses: SuxOS/.github/.github/workflows/claude-autofix.yml@main
    secrets: inherit
YAML
assert_self_has "self mode: dead workflow_run self-stub caught" "$d" "dead stub 'self-claude-autofix\.yml' triggers on workflow_run"

# 7c. A self-*.yml stub NOT on workflow_run (e.g. self-fixer-30m.yml-style cadence
#     variant) must NOT be flagged as non-canonical just for not matching a bare
#     scaffold-caller.sh name.
d="$(fresh_copy self-variant)"
cat > "$d/self-fixer-30m.yml" <<'YAML'
name: Self fixer 30m
on:
  schedule: [{ cron: "*/30 * * * *" }]
  workflow_dispatch:
jobs:
  fixer:
    uses: SuxOS/.github/.github/workflows/fixer.yml@main
    secrets: inherit
YAML
assert_self_clean "self mode: non-workflow_run self-* variant not flagged" "$d"

# 7d. (d) STALE REF (#362): self mode is name-independent for (d) same as it is for the
#     workflow_run dead-stub sub-case of (b) — a self-*.yml stub pinned off @main must be
#     caught even though the naming-derived checks (a)/(c) stay off in self mode.
d="$(fresh_copy self-stale-ref)"
sed -i 's#workflows/audit.yml@main#workflows/audit.yml@v1.2.3#' "$d/audit.yml"
assert_self_has "self mode: stale non-@main ref caught" "$d" "stub wires audit\.yml at @v1\.2\.3"

if [ "$failures" -gt 0 ]; then echo; echo "$failures assertion(s) failed"; exit 1; fi
echo; echo "all caller-conformance assertions passed"
